### ISSUE TITLE
tricontourf or tricontour cannot be used in quadrilateral mesh

### ISSUE THREAD

**Issue by jiaqiwang969** [FlowModelingControl/flowtorch#28]
Hi, sir
I am trying to use this package. 
When  quadrilateral mesh is imported,  the map is not exactly right.

Thanks

**Comment by AndreWeiner** [comment]
Hi @jiaqiwang969,
could you please provide some more context? From which format are you importing? Can you show a comparison between what you expect and how it actually looks like?
Best, Andre

**Comment by jiaqiwang969** [comment]
![image](https://user-images.githubusercontent.com/76413247/146608286-be4c5d80-ebcd-4210-a276-4aed3a9f9a55.png)

I am using the openfoam form, which is similar to of_cyliner_binary.

**Comment by jiaqiwang969** [comment]
I have checked that Tricontour cannot deal with quadrilateral mesh but with smooth Delaunay method, which make the mistake from my case.

**Comment by AndreWeiner** [comment]
The dataloaders give you access to points (vertices) and field values defined in those vertices. In the case of OpenFOAM, the mesh topology is completely ignored, so it doesn't matter what type of cells the mesh is made of. What you get from `loader.vertices` is a tensor containing all cell centers. The easiest way to visualize a field defined in an unstructured set of points is to triangulate the points and interpolate the field values within the triangles. That's what [tricontourf](https://matplotlib.org/stable/plot_types/unstructured/tricontourf.html#sphx-glr-plot-types-unstructured-tricontourf-py) does (triangulation and interpolation).
Best, Andre
