### ISSUE TITLE
Functionality of POD

### ISSUE THREAD

**Issue by kowshik96** [FlowModelingControl/flowtorch#37]
Hi Andre,

I was using the Flowtorch library to perform snapshot POD. After loading initial data and creating an instance of POD class, when I call on the **_compute_decomposition_** method it throws an error. 

` 17 def compute_decomposition(self, mode="snapshot", solver="svd", device="cpu", precision="single"):
     18     if mode == "snapshot":
---> 19         data_matrix = self._data.get_data_matrix()
     20         if not data_matrix.device == device:
     21             data_matrix.to(device=device)

AttributeError: 'Tensor' object has no attribute 'get_data_matrix'`

The data was passed as a tensor to the POD class, as expected by its constructor class. 

I was also unable to find any implementation of the **_get_data_matrix_** method. Is this functionality available? Can POD be performed using the given script?

**Comment by AndreWeiner** [comment]
Hi Kowshik,
the POD class is just an experimental leftover from the initial development of flowtorch. Instead, use `flowtorch.analysis.SVD`. Have a look at [this tutorial](https://flowmodelingcontrol.github.io/flowtorch-docs/1.1/notebooks/svd_cylinder.html) for a reference.
Best, Andre

**Comment by kowshik96** [comment]
ok thank you
