### ISSUE TITLE
SVD code

### ISSUE THREAD

**Issue by JOEJOEJOE1231231231231** [FlowModelingControl/flowtorch#39]
I'm sorry to bother you.Why choose z-component to build a data matrix
![image](https://github.com/FlowModelingControl/flowtorch/assets/150024006/c11c7b41-7db0-4d23-b72a-6d5a41b8917b)
[Doc1.pdf](https://github.com/FlowModelingControl/flowtorch/files/13266083/Doc1.pdf)

**Comment by AndreWeiner** [comment]
Hi,
the dataset comes from a 2D simulation of the flow past a cylinder. The field used in the analysis is the vorticity. The vorticity vector is defined as the curl of the velocity vector. For a 2D flow in the x-y-plane, there is only one nonzero vorticity component (z-component in this case).
Best, Andre

**Comment by JOEJOEJOE1231231231231** [comment]
Thank you ！！！！！！
