### ISSUE TITLE
FOAMDatalaoder

### ISSUE THREAD

**Issue by JOEJOEJOE1231231231231** [FlowModelingControl/flowtorch#40]
I am sorry to bother you again.When I used Flowtorch to import data calculated by myself using Open Foam, the following error was reported. May I ask what happened to you
![image](https://github.com/FlowModelingControl/flowtorch/assets/150024006/f9312158-01f3-4eb1-811e-cde75c4af262)

**Comment by AndreWeiner** [comment]
Hi there,
flowTorch is not designed and tested for Windows, particularly when it comes to parsing data. Moreover, the FOAMDataloader class is implemented for the ESI branch of OpenFOAM, i.e., openfoam.com
You can try to run your script on Linux, and it should work. If you prefer to work on Windows, you can also load the data on Linux, save the data using NumPy or PyTorch, and load the data for analysis on Windows.
Best, Andre

**Comment by JOEJOEJOE1231231231231** [comment]
Thank You ！！！！！！！！！
