### ISSUE TITLE
FoamDataloader

### ISSUE THREAD

**Issue by JOEJOEJOE1231231231231** [FlowModelingControl/flowtorch#42]
Hello：
     I ran my example on Linux this time, but still reported the following error. I tried other examples and reported the same error. But I ran your SVD decomposition code for the flow past a cylinder and it worked perfectly. So I checked the blockMesh file of the cylinder flow around the dataset you provided. The grid settings are as follows. Is this error related to this setting?
![image](https://github.com/FlowModelingControl/flowtorch/assets/150024006/3d67e44f-b8af-4aa1-bc9d-5ccdcf9431f5)
![image](https://github.com/FlowModelingControl/flowtorch/assets/150024006/3eb5738d-82a2-4a19-ac39-96959cf3f771)

**Comment by AndreWeiner** [comment]
The error happens when parsing the mesh data. Are you sure a valid mesh was created (e.g., can you open and visualize the mesh in ParaView)? If so, there seems to be something wrong with the file header of `constant/polyMesh/owner`.
Two options:
- pre-compute the cell centers and volumes using
```
postProcess -func "writeCellCentres" -constant -time none
postProcess -func "writeCellVolumes" -constant -time none
```
- zip the **clean** test case and attach to this issue
Best, Andre

**Comment by JOEJOEJOE1231231231231** [comment]
[SandiaD_LTS1.zip](https://github.com/FlowModelingControl/flowtorch/files/13365161/SandiaD_LTS1.zip)
This is a case in the openfoam/tutorials/collaboration/reatingFoam/RAS directory. I looked at the polymesh/owner file and it seems that there is indeed a problem, but I don't know how to solve it.

**Comment by AndreWeiner** [comment]
Thanks for uploading the case files. The problem is with your OpenFOAM version, which is a special compilation by some commercial company:
```
/*--------------------------------*- C++ -*----------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     | Website:  https://openfoam.org
    \\  /    A nd           | Version:  dev
     \\/     M anipulation  |

   OpenFOAM for Windows 20.09 (v1)
   Built by CFD Support, www.cfdsupport.com (based on Symscape).
\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      binary;
    class       labelList;
    note        "nPoints: 10613 nCells: 5170 nFaces: 20771 nInternalFaces: 10159";
    location    "constant/polyMesh";
    object      owner;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
```
As mentioned before, flowTorch only supports the ESI OpenFOAM version, which is the one available at www.openfoam.com
Best regards,
Andre

**Comment by JOEJOEJOE1231231231231** [comment]
THANK YOU !!!
THANK YOU!!!!
THANK YOU!!!

**Comment by JOEJOEJOE1231231231231** [comment]
![image](https://github.com/FlowModelingControl/flowtorch/assets/150024006/2bafe833-4a9c-4cdc-9159-187647727d86)
This version doesn't work, does it?

**Comment by AndreWeiner** [comment]
No, that's openfoam.**org**.

**Comment by JOEJOEJOE1231231231231** [comment]
Thank you !

**Comment by JOEJOEJOE1231231231231** [comment]
Hello：
Running code that pre calculates the unit center and volume can effectively solve this problem, and doing so can run flowtorch on the org version of Openfoam

**Comment by JOEJOEJOE1231231231231** [comment]
Running code that pre calculates the unit center and volume can effectively solve this problem, and doing so can run flowtorch on the org version of Openfoam
