### ISSUE TITLE
data matrix

### ISSUE THREAD

**Issue by JOEJOEJOE1231231231231** [FlowModelingControl/flowtorch#43]
HELLO
  I see that when constructing the data matrix, you place the example data after each column of the data matrix for SVD decomposition, so the left singular matrix is the POD mode. Can I place the data from the example in each row of the data matrix and perform SVD decomposition, where the right singular matrix is POD mode. For example, the number of rows in a data matrix is the number of snapshots, and the number of columns is the number of grid points. Is this flow torch supported?

![image](https://github.com/FlowModelingControl/flowtorch/assets/150024006/6c0243e4-3367-49d9-8311-4e97f91dd7ce)

**Comment by AndreWeiner** [comment]
Hi,
yes, in principle, you could swap rows and columns. The result stays the same:
$\hat{X}=X^T =( USV^T)^T = VSU^T=\hat{U}\hat{S}\hat{V}^T$
So, the row vectors of $\hat{V}^T$ are now your POD modes (the eigenvectors of $XX^T$).
Best, Andre
