### ISSUE TITLE
csvdataloader

### ISSUE THREAD

**Issue by JOEJOEJOE1231231231231** [FlowModelingControl/flowtorch#44]
Hello
    Can csvdataloader load data like foamdataloader? If possible, is the data format. csv or. dat? How can I use Openfoam to calculate the results and obtain CSV data?I used Paraview to extract data at a certain section and output it in CSV format. However, when I imported it using csvdataloader, the following error occurred
![image](https://github.com/FlowModelingControl/flowtorch/assets/150024006/ad1c8ab2-f485-43f5-a68e-fc3d9630bf5e)

**Comment by AndreWeiner** [comment]
Hi,
the CSVDataloader has a constructor function to load CSV files generated by OpenFOAM's sampling function object. E.g., if you sample a plane as follows:
```
surface
{
    type            surfaces;
    libs            (sampling);
    writeControl    writeTime;

    surfaceFormat   raw;
    fields          (total(p)_coeff yPlus p rho T);

    // interpolationScheme cellPoint;  //<- default

    surfaces
    {
        airfoil
        {
            type            patch;
            patches         (airfoil);
            interpolate     true;
            invariant       true;  // Unaffected by mesh motion
            surfaceFormat   raw;
        }
    }
}
```
You can load the sample output as follows:
```
# you will need to adjust the path
path = "postProcessing/surfaces"
loader = CSVDataloader.from_foam_surface(path, "total(p)_coeff_airfoil.raw")
times = loader.write_times
fields = loader.field_names[times[0]]
```
If you want to parse ParaView CSV output, I suggest using the Pandas [read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) function directly.
Best, Andre

**Comment by JOEJOEJOE1231231231231** [comment]
It's difficult for me to calculate again with Openfoam. Can I use the postprocess to call the surface function?

**Comment by JOEJOEJOE1231231231231** [comment]
Hi，
I have successfully imported the org version of Openfoam data using the CSV dataloader of Flow Torch and completed SVD decomposition. Thank you very much！
